### ISSUE TITLE
Errors building with Swift 4.0.3

### ISSUE THREAD

**Issue by refi64** [vapor/async#74]
Was trying to build Console 3.0.0-rc.1, but I got this:

```
Compile Swift Module 'Async' (45 sources)
/home/ryan/stuff/swiftver/.build/checkouts/async.git--5886762718721215692/Sources/Async/Socket/SocketSource.swift:172:40: error: missing argument for parameter 'capacity' in call
        buffer.baseAddress?.deallocate()
                                       ^
                                       capacity: <#Int#>
Swift.UnsafeMutablePointer:273:17: note: 'deallocate(capacity:)' declared here
    public func deallocate(capacity: Int)
                ^
/home/ryan/stuff/swiftver/.build/checkouts/async.git--5886762718721215692/Sources/Async/Futures/Future+Flatten.swift:51:39: error: cannot convert value of type 'Self.IndexDistance' to expected argument type 'Int'
        elements.reserveCapacity(self.count)
                                 ~~~~~^~~~~
                                 Int(      )
/home/ryan/stuff/swiftver/.build/checkouts/async.git--5886762718721215692/Sources/Async/EventLoop/Epoll/EpollEventSource.swift:139:28: error: missing argument for parameter 'capacity' in call
        pointer.deallocate()
                           ^
                           capacity: <#Int#>
Swift.UnsafeMutablePointer:273:17: note: 'deallocate(capacity:)' declared here
    public func deallocate(capacity: Int)
                ^
error: terminated(1): /usr/bin/swift-build-tool -f /home/ryan/stuff/swiftver/.build/debug.yaml swiftix.exe
```

:thinking:

**Comment by joscdk** [comment]
To my knowledge, Vapor 3 only works with Swift 4.1

**Comment by refi64** [comment]
Ohh...that makes sense...sorry for the noise!
